# Default values for knative-service-mesh-onboarding.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# name is the tenant name.
name: ""

# namespaces is the set of namespaces a tenant owns.
namespaces: [ ]

# Cluster information
cluster:
  # Kubernetes cluster domain
  domain: "cluster.local"

# Eventing-related configurations
serving:
  receivers:
    - name: "activator"
      shortName: "activator"
eventing:
  receivers:
    - name: "imc-dispatcher"
      shortName: "imc"
    - name: "kafka-broker-receiver"
      shortName: "ekb"
    - name: "kafka-channel-receiver"
      shortName: "ekc"
    - name: "kafka-sink-receiver"
      shortName: "eks"
    - name: "broker-ingress"
      shortName: "broker-ingress"
  sendersServiceAccounts:
    - name: "pingsource-mt-adapter"
      shortName: "pingsource"
    - name: "imc-dispatcher"
      shortName: "imc"
    - name: "mt-broker-filter"
      shortName: "broker-filter"
    - name: "knative-kafka-source-data-plane"
      shortName: "eks"
    - name: "knative-kafka-broker-data-plane"
      shortName: "ekb"
    - name: "knative-kafka-channel-data-plane"
      shortName: "ekc"
  reply:
    # Exclude reply-related authorization policies
    exclude: false
