{{- range $ns := $.Values.namespaces }}
---
# Allow namespace {{ $ns }} to receive requests from Knative system components.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-from-knative
  namespace: {{ $ns }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              {{- range $v := $.Values.namespaces }}
              - "{{ $v }}"
              {{- end }}
              - "knative-serving"
              - "istio-system"
    - from:
        - source:
            namespaces:
              - "knative-eventing"
      when:
        - key: request.headers[Kn-Namespace]
          values:
          {{- range $v := $.Values.namespaces }}
          - "{{ $v }}"
          {{- end }}
---
{{- end }}
