---
# Allow Knative Broker with class MTChannelBasedBroker to receive requests from {{ join "," $.Values.namespaces }}.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-mt-channel-based-broker
  namespace: knative-eventing
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "broker-ingress"
  rules:
    - from:
        - source:
            namespaces:
            {{- range $v := $.Values.namespaces }}
            - "{{ $v }}"
            {{- end }}
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
---
