{{- range $component := $.Values.serving.receivers }}
{{- range $sa := $.Values.eventing.sendersServiceAccounts }}
---
# Allow {{ $component.name }} to receive requests from {{ $sa.name }} in knative-eventing.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-{{ $sa.shortName }}-to-{{ $component.shortName }}
  namespace: knative-serving
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "{{ $component.name }}"
  rules:
    - from:
        - source:
            namespaces: [ "knative-eventing" ]
            principals: [ "cluster.local/ns/knative-eventing/sa/{{ $sa.name }}" ]
      to:
        - operation:
            hosts:
            {{- range $v := $.Values.namespaces }}
            - "*.{{ $v }}.svc.{{ $.Values.cluster.domain }}"
            {{- end }}
            methods: [ "POST" ]
---
{{ end }}
{{ end }}