{{- range $component := $.Values.eventing.receivers }}
{{- range $sa := $.Values.eventing.sendersServiceAccounts }}
---
# Allow {{ $component }} to receive requests from KafkaSources in {{ join "," $.Values.namespaces }}.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-{{ $sa }}-to-{{ $component }}
  namespace: knative-eventing
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "{{ $component }}"
  rules:
    - from:
        - source:
            namespaces: [ "knative-eventing" ]
            principals: [ "cluster.local/ns/knative-eventing/sa/{{ $sa }}" ]
      to:
        - operation:
            hosts:
            {{- range $v := $.Values.namespaces }}
            - "*.{{ $v }}.svc.{{ $.Values.cluster.domain }}"
            {{- end }}
            methods: [ "POST" ]
    - from:
        - source:
            namespaces: [ "knative-eventing" ]
            principals: [ "cluster.local/ns/knative-eventing/sa/{{ $sa }}" ]
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
---
{{ end }}
{{ end }}