{{ if eq $.Values.reply.exclude false }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-mt-channel-based-broker-reply
  namespace: knative-eventing
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "broker-ingress"
  rules:
    - from:
        - source:
            namespaces:
            - "knative-eventing"
            principals:
            - "cluster.local/ns/knative-eventing/sa/imc-dispatcher"
            - "cluster.local/ns/knative-eventing/sa/mt-broker-filter"
            - "cluster.local/ns/knative-eventing/sa/kafka-channel-dispatcher"
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
---
{{ end }}
