{{- range $ns := $.Values.namespaces }}
---
# Enforce peer authentication to be mTLS in the namespace {{ $ns }}, so that we can define
# authorization policies based on client and server identities.
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ $ns }}
spec:
  mtls:
    mode: STRICT
---
{{ end }}