{{- if .Values.enableServing }}
{{- range $ns := $.Values.namespaces }}
---
# The peer-authentication.yaml enables mTLS, but
# as this is not working for DomainMappings, these DestinationRules enforce mTLS also on the service level.
# This forces the istio-ingressgateway to also send mTLS if the destination is itself.
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: enforce-mtls-in-namespace
  namespace: {{ $ns }}
spec:
  host: "*.{{ $ns }}.svc.cluster.local"
  trafficPolicy:
    tls: ISTIO_MUTUAL
---
{{ end }}
{{ end }}
