{{- if .Values.enableServing }}
{{- range $ns := $.Values.namespaces }}
---
# Allow kubernetes to call the PreStopHook to wait for draining on port 8022 in ns {{ $ns }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "allow-wait-for-drain"
  namespace: {{ $ns | quote }}
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            ports:
              - "8022"
---
{{ end }}
{{ end }}